# Generated by Django 2.2.1 on 2020-08-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_app', '0002_todo_isdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='isUpdate',
            field=models.BooleanField(default=False),
        ),
    ]
